//! The `.MPF` model point reader (`04-verify.md` §4.1).
//!
//! The load-bearing rule is §4.1.4: **the column-name line is the last non-`*`,
//! non-comment line before the first `*` row that is not a recognised header
//! key.** Different Prophet releases either carry the names as the payload of
//! `OUTPUT_FORMAT` or put them on a bare line of their own, and no release marks
//! which it did — so the reader positions the names structurally, and when both
//! forms are present and disagree it refuses (`P0103`) rather than picking one.

use std::collections::{BTreeMap, BTreeSet};
use std::ops::Range;

use predictable_diagnostics::{Diagnostic, Span, Suggestion};
use predictable_ir::{DType, Unit};

use crate::common::{header_entry, is_comment, Cell, Header, Read};
use crate::text::{
    detect_encoding, is_identifier, lines, snake_case, split_fields, Encoding, Field,
};

/// Header keys the `.MPF` reader recognises (§4.1.3).
pub const RECOGNISED_KEYS: &[&str] = &[
    "OUTPUT_FORMAT",
    "VARIABLE_TYPES",
    "NUMLINES",
    "MPF_VERSION",
    "SPCODE_SET",
    "DATE_FORMAT",
];

/// The order of the day and month components in slash-separated dates.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum DateOrder {
    /// Not yet known — the reader refuses to guess (`P0109`).
    #[default]
    Unknown,
    /// `DD/MM/YYYY`.
    DayFirst,
    /// `MM/DD/YYYY`.
    MonthFirst,
}

/// Caller-supplied decisions the file itself cannot settle.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct MpfOptions {
    /// Overrides both `DATE_FORMAT` and the data-driven inference.
    pub date_order: Option<DateOrder>,
}

/// One column of an `.MPF`.
#[derive(Debug, Clone, PartialEq)]
pub struct MpfColumn {
    /// Snake-cased name used in the IR (`SUM_ASSURED` → `sum_assured`).
    pub name: String,
    /// The original Prophet name, preserved in `meta.source.column`.
    pub source_name: String,
    /// The `VARIABLE_TYPES` letter, upper-cased.
    pub type_letter: char,
    /// The IR dtype the letter maps to (§4.1.5).
    pub dtype: DType,
    /// Always `Unit::None` — guessing `money` vs `count` is refused (§4.1.8).
    pub unit: Unit,
    /// Byte range of the name in the name line.
    pub span: Range<usize>,
}

/// A parsed `.MPF`.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct MpfFile {
    /// The file name the spans point into.
    pub file: String,
    /// How the bytes were decoded.
    pub encoding: Option<Encoding>,
    /// Comments, recognised keys and retained unknown keys.
    pub header: Header,
    /// Columns, in file order.
    pub columns: Vec<MpfColumn>,
    /// Data rows, each with one cell per column (the leading `*` is not a cell).
    pub rows: Vec<Vec<Cell>>,
    /// Distinct values of each `S`/`T` column, capped at 64 (§4.1.9).
    pub distinct: BTreeMap<String, Vec<String>>,
    /// Columns whose distinct set hit the 64-value cap.
    pub distinct_truncated: BTreeSet<String>,
    /// The date order actually used, once resolved.
    pub date_order: DateOrder,
}

impl MpfFile {
    /// The column with this snake-cased name.
    pub fn column(&self, name: &str) -> Option<&MpfColumn> {
        self.columns.iter().find(|c| c.name == name)
    }

    /// The cell at `(row, column-name)`.
    pub fn cell(&self, row: usize, name: &str) -> Option<&Cell> {
        let idx = self.columns.iter().position(|c| c.name == name)?;
        self.rows.get(row)?.get(idx)
    }

    /// Long-lived, boring, and exactly what the Parquet writer consumes: the rows
    /// as CSV with snake-cased headers.
    pub fn to_csv(&self) -> String {
        let mut out = String::new();
        let names: Vec<&str> = self.columns.iter().map(|c| c.name.as_str()).collect();
        out.push_str(&names.join(","));
        out.push('\n');
        for row in &self.rows {
            let cells: Vec<String> = row.iter().map(Cell::to_csv_field).collect();
            out.push_str(&cells.join(","));
            out.push('\n');
        }
        out
    }

    /// The `[[modelpoint_field]]` fragment for `model.pir`, plus the proposed
    /// `[[enum]]` blocks of §4.1.9.
    ///
    /// `unit` is `none` everywhere and `key` is `false` everywhere on purpose:
    /// both are review steps for the migrating agent, not inferences.
    pub fn to_fragment_toml(&self) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "# generated by `predictable prophet mpf` from {}\n\
             # review: set `unit` on every numeric field, and mark exactly one field `key = true`.\n",
            self.file
        ));
        for col in &self.columns {
            let dtype = if self.gender_enum_column() == Some(col.name.as_str()) {
                "enum(Gender)".to_string()
            } else {
                col.dtype.to_string()
            };
            out.push_str("\n[[modelpoint_field]]\n");
            out.push_str(&format!("name = \"{}\"\n", col.name));
            out.push_str(&format!("dtype = \"{dtype}\"\n"));
            out.push_str("unit = \"none\"\n");
            out.push_str("required = true\n");
            out.push_str("key = false\n");
            out.push_str(&format!(
                "meta.source = {{ file = \"{}\", column = \"{}\", type_letter = \"{}\" }}\n",
                self.file, col.source_name, col.type_letter
            ));
        }
        for (col, values) in &self.distinct {
            let quoted: Vec<String> = values.iter().map(|v| format!("\"{v}\"")).collect();
            let truncated = if self.distinct_truncated.contains(col) {
                "  # truncated at 64 distinct values\n"
            } else {
                ""
            };
            if self.gender_enum_column() == Some(col.as_str()) {
                out.push_str("\n[[enum]]\nname = \"Gender\"\n");
                out.push_str(&format!("variants = [{}]\n", quoted.join(", ")));
            } else {
                out.push_str(&format!(
                    "\n# proposed enum for `{col}` — the field stays `str` until you accept it\n"
                ));
                out.push_str(truncated);
                out.push_str(&format!(
                    "# [[enum]]\n# name = \"{}\"\n# variants = [{}]\n",
                    pascal_case(col),
                    quoted.join(", ")
                ));
            }
        }
        out
    }

    /// The column, if any, whose distinct set is exactly `{M, F}` — the one case
    /// §4.1.9 promotes to `enum(Gender)` without asking.
    pub fn gender_enum_column(&self) -> Option<&str> {
        self.distinct.iter().find_map(|(col, values)| {
            let set: BTreeSet<&str> = values.iter().map(String::as_str).collect();
            (set == BTreeSet::from(["F", "M"])).then_some(col.as_str())
        })
    }
}

fn pascal_case(name: &str) -> String {
    name.split('_')
        .filter(|s| !s.is_empty())
        .map(|s| {
            let mut c = s.chars();
            match c.next() {
                Some(f) => f.to_ascii_uppercase().to_string() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn dtype_for(letter: char) -> Option<DType> {
    Some(match letter {
        'I' => DType::I64,
        'N' => DType::F64,
        'S' | 'T' => DType::Str,
        'D' => DType::Date,
        'B' => DType::Bool,
        _ => return None,
    })
}

/// Read a `.MPF`. Pure: bytes in, value and diagnostics out, no IO, no panics.
pub fn read_mpf(bytes: &[u8], file: &str, options: &MpfOptions) -> Read<MpfFile> {
    let mut diags: Vec<Diagnostic> = Vec::new();
    let mut mpf = MpfFile {
        file: file.to_string(),
        ..MpfFile::default()
    };

    let (encoding, bad_at) = detect_encoding(bytes);
    mpf.encoding = Some(encoding);
    if let Some(at) = bad_at {
        diags.push(
            Diagnostic::new(
                "P0101",
                "file is not valid utf-8; decoded as windows-1252".to_string(),
            )
            .span(Span::primary(file, at..(at + 1).min(bytes.len())).label("first non-utf-8 byte"))
            .note(
                "re-encode the file as UTF-8 to remove this lint; the import proceeds either way",
            ),
        );
    }

    let all = lines(bytes);
    let mut header = Header::default();
    let mut candidates: Vec<(usize, Vec<Field>, Range<usize>)> = Vec::new();
    let mut data_lines = Vec::new();
    let mut seen_star = false;

    for line in &all {
        let line = line.trimmed();
        if line.is_blank() {
            continue;
        }
        if is_comment(&line) {
            header.comments.push(line.text());
            continue;
        }
        if line.bytes.first() == Some(&b'*') {
            seen_star = true;
            data_lines.push(line);
            continue;
        }
        if seen_star {
            // Trailing non-comment junk after the data block: retained as a comment
            // rather than silently dropped.
            header.comments.push(line.text());
            continue;
        }
        let entry = header_entry(&line);
        if RECOGNISED_KEYS.contains(&entry.key.as_str()) {
            header.entries.insert(entry.key.clone(), entry);
        } else {
            candidates.push((line.number, split_fields(&line), line.range()));
        }
    }

    // §4.1.3: every unrecognised header key but the last one is retained verbatim.
    let name_line = candidates.pop();
    for (_, fields, span) in &candidates {
        let key = fields.first().map(Field::key).unwrap_or_default();
        let rest: Vec<String> = fields[1.min(fields.len())..]
            .iter()
            .map(|f| f.text.clone())
            .collect();
        header.extra.insert(key.clone(), rest.join(","));
        diags.push(
            Diagnostic::new(
                "P0102",
                format!("unrecognised header key `{key}` retained verbatim"),
            )
            .span(Span::primary(file, span.clone()).label("kept in `header.extra`")),
        );
    }

    // §4.1.4: `OUTPUT_FORMAT` may carry the names itself.
    let of_names: Option<(Vec<Field>, Range<usize>)> = header.get("OUTPUT_FORMAT").and_then(|e| {
        let looks_like_names =
            e.payload.len() >= 2 && e.payload.iter().all(|f| is_identifier(&f.text));
        looks_like_names.then(|| (e.payload.clone(), e.span.clone()))
    });

    let names: Vec<Field> = match (&name_line, &of_names) {
        (Some((_, fields, span)), Some((of_fields, of_span))) => {
            let a: Vec<&str> = fields.iter().map(|f| f.text.as_str()).collect();
            let b: Vec<&str> = of_fields.iter().map(|f| f.text.as_str()).collect();
            if a != b {
                diags.push(
                    Diagnostic::new(
                        "P0103",
                        format!(
                            "`OUTPUT_FORMAT` names {} column(s) but the name line names {}",
                            b.len(),
                            a.len()
                        ),
                    )
                    .span(
                        Span::primary(file, span.clone())
                            .label(format!("name line: {}", a.join(","))),
                    )
                    .span(
                        Span::secondary(file, of_span.clone())
                            .label(format!("`OUTPUT_FORMAT`: {}", b.join(","))),
                    )
                    .note(
                        "delete one of the two, or make them identical; the reader will not choose",
                    ),
                );
            }
            fields.clone()
        }
        (Some((_, fields, _)), None) => fields.clone(),
        (None, Some((of_fields, _))) => of_fields.clone(),
        (None, None) => Vec::new(),
    };

    if names.is_empty() {
        diags.push(
            Diagnostic::new(
                "P0110",
                "no column-name line found before the first `*` data row",
            )
            .span(Span::primary(file, 0..bytes.len().min(1)).label("in this file"))
            .note(
                "the column names are the last non-`*`, non-comment line before the first `*` \
                     row that is not a recognised header key (04-verify.md §4.1.4)",
            ),
        );
        mpf.header = header;
        return Read {
            value: mpf,
            diagnostics: diags,
        };
    }

    // §4.1.5: `VARIABLE_TYPES` maps positionally onto the names.
    let types: Vec<Field> = header
        .get("VARIABLE_TYPES")
        .map(|e| e.payload.clone())
        .unwrap_or_default();
    let vt_span = header
        .get("VARIABLE_TYPES")
        .map(|e| e.span.clone())
        .unwrap_or(0..0);
    if types.len() != names.len() {
        let first_missing = names
            .get(types.len())
            .map(|f| f.text.clone())
            .unwrap_or_else(|| "<none>".to_string());
        let message = if types.is_empty() {
            format!(
                "`VARIABLE_TYPES` is missing; {} column(s) have no declared type",
                names.len()
            )
        } else {
            format!(
                "`VARIABLE_TYPES` declares {} type(s) but the name line has {} column(s); \
                 first column without a type is `{first_missing}`",
                types.len(),
                names.len()
            )
        };
        diags.push(
            Diagnostic::new("P0104", message)
                .span(
                    Span::primary(file, names[0].start..names[names.len() - 1].end)
                        .label(format!("{} column names", names.len())),
                )
                .span(Span::secondary(file, vt_span).label(format!("{} type letters", types.len())))
                .note("every column is read as `str` until the two agree"),
        );
    }

    for (i, name) in names.iter().enumerate() {
        let letter = types
            .get(i)
            .and_then(|f| f.text.chars().next())
            .map(|c| c.to_ascii_uppercase())
            .unwrap_or('S');
        let dtype = match dtype_for(letter) {
            Some(d) => d,
            None => {
                diags.push(
                    Diagnostic::new(
                        "P0104",
                        format!(
                            "unknown `VARIABLE_TYPES` letter `{letter}` for column `{}`",
                            name.text
                        ),
                    )
                    .span(
                        Span::primary(file, types[i].range())
                            .label("expected one of I, N, S, T, D, B"),
                    )
                    .note("the column is read as `str`"),
                );
                DType::Str
            }
        };
        mpf.columns.push(MpfColumn {
            name: snake_case(&name.text),
            source_name: name.text.clone(),
            type_letter: letter,
            dtype,
            unit: Unit::None,
            span: name.range(),
        });
    }

    // §4.1.7: settle the date order once, from `DATE_FORMAT`, the caller, or the
    // data — and refuse when none of the three can.
    let date_cols: Vec<usize> = mpf
        .columns
        .iter()
        .enumerate()
        .filter(|(_, c)| c.dtype == DType::Date)
        .map(|(i, _)| i)
        .collect();
    let rows_raw: Vec<Vec<Field>> = data_lines.iter().map(|l| split_fields(l)).collect();
    let (order, order_diag) =
        resolve_date_order(file, options, &header, &date_cols, &rows_raw, &mpf.columns);
    mpf.date_order = order;
    diags.extend(order_diag);

    // §4.1.6 and §4.1.7: rows.
    let mut percent_columns: BTreeSet<usize> = BTreeSet::new();
    let expected = mpf.columns.len() + 1; // the leading `*` marker
    for (line, fields) in data_lines.iter().zip(rows_raw.iter()) {
        if fields.len() != expected {
            let code = if fields.len() < expected {
                "P0105"
            } else {
                "P0106"
            };
            diags.push(
                Diagnostic::new(
                    code,
                    format!(
                        "data row on line {} has {} field(s); the header declares {} column(s)",
                        line.number,
                        fields.len() - 1,
                        mpf.columns.len()
                    ),
                )
                .span(Span::primary(file, line.range()).label(line.text()))
                .note("the row is skipped; no padding and no truncation happens"),
            );
            continue;
        }
        let mut row = Vec::with_capacity(mpf.columns.len());
        for (i, col) in mpf.columns.iter().enumerate() {
            let field = &fields[i + 1];
            let (cell, percent, bad) = parse_cell(col, field, order);
            if percent {
                percent_columns.insert(i);
            }
            if bad {
                diags.push(
                    Diagnostic::new(
                        "P0111",
                        format!(
                            "`{}` on line {} is not a valid `{}` value for column `{}`",
                            field.text, line.number, col.type_letter, col.source_name
                        ),
                    )
                    .span(Span::primary(file, field.range()).label(format!(
                        "declared `{}` ({})",
                        col.type_letter, col.dtype
                    )))
                    .note("the cell is read as null; fix the source or change the `VARIABLE_TYPES` letter"),
                );
            }
            row.push(cell);
        }
        mpf.rows.push(row);
    }

    for i in percent_columns {
        let col = &mpf.columns[i];
        diags.push(
            Diagnostic::new(
                "P0108",
                format!(
                    "column `{}` contains `%` values; they were divided by 100",
                    col.source_name
                ),
            )
            .span(Span::primary(file, col.span.clone()).label("percentage column"))
            .note(
                "declare the field's `unit` explicitly so the conversion is visible in the model",
            ),
        );
    }

    // §4.1.6: `NUMLINES` never wins.
    if let Some(entry) = header.get("NUMLINES") {
        if let Ok(declared) = entry.value().trim().parse::<usize>() {
            if declared != mpf.rows.len() {
                diags.push(
                    Diagnostic::new(
                        "P0107",
                        format!(
                            "`NUMLINES` says {declared} but the file has {} data row(s)",
                            mpf.rows.len()
                        ),
                    )
                    .span(Span::primary(file, entry.span.clone()).label("declared row count"))
                    .note("the data wins; `NUMLINES` is not used to size anything"),
                );
            }
        }
    }

    // §4.1.9: distinct value sets for the string columns.
    for (i, col) in mpf.columns.iter().enumerate() {
        if !matches!(col.type_letter, 'S' | 'T') {
            continue;
        }
        let mut set: BTreeSet<String> = BTreeSet::new();
        let mut truncated = false;
        for row in &mpf.rows {
            if let Some(Cell::Str(v)) = row.get(i) {
                if set.len() >= 64 && !set.contains(v) {
                    truncated = true;
                    continue;
                }
                set.insert(v.clone());
            }
        }
        if truncated {
            mpf.distinct_truncated.insert(col.name.clone());
        }
        mpf.distinct
            .insert(col.name.clone(), set.into_iter().collect());
    }

    // §4.1.8: units are never guessed.
    for col in &mpf.columns {
        if col.dtype == DType::F64 {
            diags.push(
                Diagnostic::new(
                    "W0102",
                    format!(
                        "numeric column `{}` imported with `unit = \"none\"`",
                        col.source_name
                    ),
                )
                .span(Span::primary(file, col.span.clone()).label("unit not inferred"))
                .suggestion(
                    Suggestion::new(format!(
                        "set the unit on `{}` explicitly (`money`, `count`, `rate(annual)`, …)",
                        snake_case(&col.source_name)
                    ))
                    .applicability(predictable_diagnostics::Applicability::HasPlaceholders),
                ),
            );
        }
    }

    if mpf.rows.is_empty() {
        diags.push(
            Diagnostic::new(
                "P0110",
                "the file declares columns but has no `*` data rows",
            )
            .span(
                Span::primary(file, names[0].start..names[names.len() - 1].end)
                    .label("columns declared here"),
            ),
        );
    }

    mpf.header = header;
    Read {
        value: mpf,
        diagnostics: diags,
    }
}

fn parse_cell(col: &MpfColumn, field: &Field, order: DateOrder) -> (Cell, bool, bool) {
    let raw = field.text.trim();
    if raw.is_empty() {
        return (Cell::Null, false, false);
    }
    match col.dtype {
        DType::I64 => match strip_numeric(raw).0.parse::<i64>() {
            Ok(v) => (Cell::Int(v), false, false),
            Err(_) => (Cell::Null, false, true),
        },
        DType::F64 => {
            let (cleaned, percent) = strip_numeric(raw);
            match cleaned.parse::<f64>() {
                Ok(v) if v.is_finite() => (
                    Cell::Float(if percent { v / 100.0 } else { v }),
                    percent,
                    false,
                ),
                _ => (Cell::Null, percent, true),
            }
        }
        DType::Bool => match raw.to_ascii_uppercase().as_str() {
            "Y" | "YES" | "T" | "TRUE" | "1" => (Cell::Bool(true), false, false),
            "N" | "NO" | "F" | "FALSE" | "0" => (Cell::Bool(false), false, false),
            _ => (Cell::Null, false, true),
        },
        DType::Date => match parse_date(raw, order) {
            Some(iso) => (Cell::Date(iso), false, false),
            None => (Cell::Null, false, true),
        },
        _ => (Cell::Str(raw.to_string()), false, false),
    }
}

/// Strip thousands separators, spaces and a leading `+`; report a trailing `%`.
fn strip_numeric(raw: &str) -> (String, bool) {
    let percent = raw.ends_with('%');
    let body = if percent { &raw[..raw.len() - 1] } else { raw };
    let mut out = String::new();
    for (i, ch) in body.trim().chars().enumerate() {
        match ch {
            ',' | ' ' | '_' => {}
            '+' if i == 0 => {}
            other => out.push(other),
        }
    }
    (out, percent)
}

fn valid_ymd(y: i64, m: i64, d: i64) -> bool {
    (1..=9999).contains(&y) && (1..=12).contains(&m) && (1..=31).contains(&d)
}

/// Parse a Prophet date into ISO-8601. `None` means "not a date in any accepted
/// form", which is `P0111`; ambiguity is settled before this is called.
pub fn parse_date(raw: &str, order: DateOrder) -> Option<String> {
    let raw = raw.trim();
    if raw.len() == 8 && raw.bytes().all(|b| b.is_ascii_digit()) {
        let (y, m, d) = (
            raw[0..4].parse().ok()?,
            raw[4..6].parse().ok()?,
            raw[6..8].parse().ok()?,
        );
        return valid_ymd(y, m, d).then(|| format!("{y:04}-{m:02}-{d:02}"));
    }
    let sep = if raw.contains('/') {
        '/'
    } else if raw.contains('-') {
        '-'
    } else {
        return None;
    };
    let parts: Vec<&str> = raw.split(sep).collect();
    if parts.len() != 3 {
        return None;
    }
    let nums: Vec<i64> = parts.iter().filter_map(|p| p.trim().parse().ok()).collect();
    if nums.len() != 3 {
        return None;
    }
    let (y, m, d) = if parts[0].trim().len() == 4 {
        (nums[0], nums[1], nums[2])
    } else {
        match order {
            DateOrder::MonthFirst => (nums[2], nums[0], nums[1]),
            // `DayFirst` is only reached once resolved; `Unknown` never gets here
            // because the caller has already raised `P0109`.
            _ => (nums[2], nums[1], nums[0]),
        }
    };
    valid_ymd(y, m, d).then(|| format!("{y:04}-{m:02}-{d:02}"))
}

fn resolve_date_order(
    file: &str,
    options: &MpfOptions,
    header: &Header,
    date_cols: &[usize],
    rows: &[Vec<Field>],
    columns: &[MpfColumn],
) -> (DateOrder, Vec<Diagnostic>) {
    if let Some(order) = options.date_order {
        return (order, Vec::new());
    }
    if let Some(entry) = header.get("DATE_FORMAT") {
        let fmt = entry.value().to_ascii_uppercase();
        if fmt.starts_with("DD") {
            return (DateOrder::DayFirst, Vec::new());
        }
        if fmt.starts_with("MM") {
            return (DateOrder::MonthFirst, Vec::new());
        }
        if fmt.starts_with("YYYY") {
            return (DateOrder::DayFirst, Vec::new());
        }
    }

    // Evidence from the data: a first component above 12 can only be a day, a
    // second component above 12 can only be a month-position day.
    let mut day_first = false;
    let mut month_first = false;
    let mut ambiguous: Option<(usize, Range<usize>, String)> = None;
    for row in rows {
        for &c in date_cols {
            let Some(field) = row.get(c + 1) else {
                continue;
            };
            let raw = field.text.trim();
            if !raw.contains('/') {
                continue;
            }
            let parts: Vec<&str> = raw.split('/').collect();
            if parts.len() != 3 || parts[0].trim().len() == 4 {
                continue;
            }
            let a: i64 = parts[0].trim().parse().unwrap_or(0);
            let b: i64 = parts[1].trim().parse().unwrap_or(0);
            if a > 12 {
                day_first = true;
            } else if b > 12 {
                month_first = true;
            } else if ambiguous.is_none() {
                ambiguous = Some((c, field.range(), raw.to_string()));
            }
        }
    }

    match (day_first, month_first) {
        (true, false) => (DateOrder::DayFirst, Vec::new()),
        (false, true) => (DateOrder::MonthFirst, Vec::new()),
        (true, true) => {
            let span = ambiguous
                .as_ref()
                .map(|(_, r, _)| r.clone())
                .unwrap_or(0..0);
            (
                DateOrder::Unknown,
                vec![Diagnostic::new(
                    "P0109",
                    "date column contains values consistent with both `DD/MM/YYYY` and `MM/DD/YYYY`",
                )
                .span(Span::primary(file, span).label("contradictory evidence in this column"))
                .note("pass `--date-order dd/mm` or `--date-order mm/dd`, or set `DATE_FORMAT` in the file")],
            )
        }
        (false, false) => match ambiguous {
            Some((c, span, raw)) => {
                let name = columns
                    .get(c)
                    .map(|c| c.source_name.clone())
                    .unwrap_or_default();
                (
                    DateOrder::Unknown,
                    vec![Diagnostic::new(
                        "P0109",
                        format!("date order in column `{name}` cannot be resolved from the data"),
                    )
                    .span(Span::primary(file, span).label(format!("`{raw}` is valid as both DD/MM and MM/DD")))
                    .note("pass `--date-order dd/mm` or `--date-order mm/dd`, or set `DATE_FORMAT` in the file; the reader never guesses a date order")],
                )
            }
            // No slash dates at all: `YYYYMMDD` and `YYYY-MM-DD` are unambiguous.
            None => (DateOrder::DayFirst, Vec::new()),
        },
    }
}
