// Generate the Model Explorer screenshots for `docs/v2/model-explorer.md`.
//
// 05-viz.md §5.4: "Every screenshot in the docs is generated by a CI job from
// the corpus, never hand-captured." So this script starts the *real* server —
//
//     predictable serve models/term_annual/build/{schema,product,model}.pir --no-block --json
//
// — drives the *real* bundle in a browser, and writes the PNGs. Nothing here
// stubs a data source: what you see in the docs is what the engine served.
//
//     node tools/screenshots.mjs [outDir]
//
// It also doubles as the Playwright smoke test: every shot asserts something
// about the page before it is taken, and a failure exits non-zero.

import { spawn } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "../../../..");
const outDir = resolve(process.argv[2] ?? resolve(repo, "docs/v2/img"));
const model = ["schema", "product", "model"].map(
  (name) => `models/term_annual/build/${name}.pir`,
);

async function startServer() {
  // `serve` blocks (that is the point — the URL must stay alive), and its
  // stdout is flushed on exit, so the URL is collected from `--out-json`
  // instead of by parsing the stream.
  const doc = resolve(tmpdir(), `predictable-serve-${process.pid}.json`);
  rmSync(doc, { force: true });
  const child = spawn(
    "cargo",
    ["run", "-q", "-p", "predictable-cli", "--", "serve", ...model, "--out-json", doc],
    { cwd: repo, stdio: ["ignore", "inherit", "inherit"] },
  );
  let exited = false;
  child.on("exit", (code) => {
    exited = true;
    if (code !== 0) console.error(`serve exited with ${code}`);
  });
  for (let waited = 0; waited < 240_000; waited += 250) {
    if (existsSync(doc)) {
      const parsed = JSON.parse(readFileSync(doc, "utf8"));
      return { child, url: parsed.url ?? parsed.serve?.url };
    }
    if (exited) throw new Error("serve exited before it reported a URL");
    await new Promise((r) => setTimeout(r, 250));
  }
  throw new Error("serve did not report a URL in 240 s");
}

const shots = [];
async function shot(page, name, action) {
  await action(page);
  await page.waitForTimeout(250);
  const file = resolve(outDir, `${name}.png`);
  await page.screenshot({ path: file });
  shots.push(name);
}

const { child, url } = await startServer();
mkdirSync(outDir, { recursive: true });
const browser = await chromium.launch();
let failure;
try {
  for (const theme of ["light", "dark"]) {
    const context = await browser.newContext({
      viewport: { width: 1440, height: 860 },
      deviceScaleFactor: 2,
      colorScheme: theme,
    });
    const page = await context.newPage();
    page.on("pageerror", (error) => {
      failure ??= error;
    });
    await page.goto(url);
    // The layout runs in a worker; wait for it rather than for a timer.
    await page.waitForSelector("[data-testid=graph-svg]", { timeout: 60_000 });
    await page.waitForSelector("[data-testid=graph-node]");

    if (theme === "light") {
      await shot(page, "explorer-overview", async () => {});

      await shot(page, "explorer-inspector", async (p) => {
        await p.click("[data-testid=graph-node][data-id='model.num_pols_if']");
        await p.waitForSelector("[data-testid=inspector][data-id='model.num_pols_if']");
        await p.waitForSelector("[data-testid=expr-link]");
      });

      await shot(page, "explorer-impact", async (p) => {
        await p.click("[data-testid=graph-node][data-id='model.qx']");
        await p.keyboard.press("i");
        await p.waitForSelector("[data-testid=impact-count]");
      });

      await shot(page, "explorer-layers", async (p) => {
        await p.getByLabel("layers").check();
        await p.waitForSelector(".band");
      });

      await shot(page, "explorer-palette", async (p) => {
        await p.keyboard.press("Meta+k");
        await p.waitForSelector("[data-testid=palette]");
        await p.getByLabel("search components").fill("res");
        await p.waitForSelector("[data-testid=palette-hit]");
      });
    } else {
      await shot(page, "explorer-dark", async (p) => {
        await p.click("[data-testid=graph-node][data-id='model.reserve']");
        await p.waitForSelector("[data-testid=inspector][data-id='model.reserve']");
      });
    }
    await context.close();
  }
} catch (error) {
  failure = error;
} finally {
  await browser.close();
  child.kill();
}

if (failure) {
  console.error(failure);
  process.exit(1);
}
console.log(`wrote ${shots.length} screenshots to ${outDir}: ${shots.join(", ")}`);
