#!/usr/bin/env python3
"""Generate `llms-full.txt` — one fetch that primes a model completely (04-verify.md §8.3).

`llms.txt` is an index: a model that reads it still has to fetch a dozen files. `llms-full.txt`
is the concatenation of the material that is *normative* — the IR spec, the verify spec, the
cheatsheet, the diagnostics index, the migration skill, and the worked model sources — so a single
fetch is enough to write and reconcile a model.

It is generated, never hand-edited, and CI regenerates it and fails if the result differs from the
committed file or exceeds the token budget.

    python tools/gen_llms_full.py            # write llms-full.txt
    python tools/gen_llms_full.py --check    # fail if the committed file is stale
    python tools/gen_llms_full.py --stdout   # print it

Token budget: 200_000, estimated at 4 characters per token (04-verify.md §8.3).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUTPUT = REPO / "llms-full.txt"
TOKEN_BUDGET = 200_000
CHARS_PER_TOKEN = 4

HEADER = """# predictable — full context

> An open-source (MIT) actuarial modelling framework for life insurance cashflow projection.
> A Python authoring DSL compiles to a serialisable, git-diffable computation-graph IR that a Rust
> engine executes. This file is the concatenation of everything normative: the IR and verification
> specifications, the IR cheatsheet, the diagnostics index, the Prophet migration skill, and the
> worked model sources. It is generated by `tools/gen_llms_full.py` — do not edit it by hand.

The index form, with one-line annotations and links, is `llms.txt`.
"""

# (repo-relative path, the section title it appears under). Order is deliberate: the format an
# agent must write comes before the loop it must run, which comes before the codes it will hit.
SOURCES: list[tuple[str, str]] = [
    ("docs/design/01-ir.md", "The IR specification (normative)"),
    ("docs/design/04-verify.md", "The verification layer (normative)"),
    ("skills/predictable-migration/references/ir-cheatsheet.md", "IR cheatsheet"),
    ("docs/llm/diagnostics.md", "Diagnostics index"),
    ("skills/predictable-migration/SKILL.md", "The Prophet migration skill"),
    ("skills/predictable-migration/references/prophet-idioms.md", "Prophet idioms"),
    ("skills/predictable-migration/references/diagnostics.md", "Migration diagnostics"),
    ("skills/predictable-migration/references/verify-formats.md", "Verify-layer formats"),
    ("docs/v2/verification-walkthrough.md", "The verification loop, end to end"),
    ("models/term_annual/build/schema.pir", "Worked model — term assurance, schema"),
    ("models/term_annual/build/model.pir", "Worked model — term assurance, model"),
    ("models/term_annual/build/product.pir", "Worked model — term assurance, product"),
    ("models/term_annual/run.pir", "Worked model — term assurance, run"),
    ("models/ifrs17_gmm/build/model.pir", "Worked model — IFRS 17 GMM, model"),
]


def fence_for(path: str) -> str | None:
    """The code fence a non-Markdown source is wrapped in, or None for Markdown."""
    if path.endswith(".md"):
        return None
    if path.endswith(".pir"):
        return "toml"
    if path.endswith(".py"):
        return "python"
    return ""


def render(repo: Path = REPO) -> str:
    parts = [HEADER]
    missing = []
    for rel, title in SOURCES:
        path = repo / rel
        if not path.exists():
            missing.append(rel)
            continue
        body = path.read_text(encoding="utf-8").rstrip("\n")
        fence = fence_for(rel)
        if fence is not None:
            body = f"```{fence}\n{body}\n```"
        parts.append(f"\n\n---\n\n# {title}\n\nSource: `{rel}`\n\n{body}")
    if missing:
        raise SystemExit(f"gen_llms_full: these sources are missing: {missing}")
    return "\n".join(parts).rstrip("\n") + "\n"


def estimated_tokens(text: str) -> int:
    return len(text) // CHARS_PER_TOKEN


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    parser.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = parser.parse_args(argv)

    text = render()
    tokens = estimated_tokens(text)
    if tokens > TOKEN_BUDGET:
        print(
            f"llms-full.txt is ~{tokens} tokens, over the {TOKEN_BUDGET} budget; "
            "drop a source from SOURCES rather than raising the budget",
            file=sys.stderr,
        )
        return 1

    if args.stdout:
        sys.stdout.write(text)
        return 0
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != text:
            print("llms-full.txt is stale: run `python tools/gen_llms_full.py`", file=sys.stderr)
            return 1
        print(f"llms-full.txt is current (~{tokens} tokens of {TOKEN_BUDGET})")
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO)} (~{tokens} tokens of {TOKEN_BUDGET})")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
